#!/bin/bash
## jumpbox system-wide bashrc
export PS1=$(echo '[\[\e[1;33m\t\e[0m\]] \[\e[1;32m\]\u@\h\[\e[0m\] \[\e[1;34m\]\w\[\e[0m\]\n\[\e[1;34m\]\$ \[\e[0m\]')
umask 002

################################################################################
#####################################################  env vars you get for free
export DOCKER_HOST=unix:///var/vcap/sys/run/docker/docker.sock
export PATH=/var/vcap/packages/tools/bin:/var/vcap/packages/docker/bin:$PATH
